export const ActionTypes = {
	GET_ALL_GENRE: 'GET_ALL_GENRE',
	SET_ALL_GENRE: 'SET_ALL_GENRE',
	SET_ALL_GENRE_MOVIE: 'SET_ALL_GENRE_MOVIE',
	SET_ALL_CONFIGURATION: 'SET_ALL_CONFIGURATION',
	SET_MOVIE_DETAILS: 'SET_MOVIE_DETAILS',
};
